# AUTO-SUGGESTED PATTERN PACKS - GENERATED BY PATTERN_PACKS_LAB.PY
# DO NOT EDIT THIS FILE DIRECTLY - REVIEW AND MERGE INTO pattern_packs.py MANUALLY
# Generated on: 2025-11-30 10:44:37

# Golden Days Based Pattern Suggestions

# Number Range Patterns
# GOLDEN_LOW_RANGE: 25.0% hit rate
SUGGESTED_RANGE_LOW_RANGE = list(range(10, 40))

# GOLDEN_MID_RANGE: 56.2% hit rate
SUGGESTED_RANGE_MID_RANGE = list(range(40, 70))

# Tens Digit Patterns
# STRONG_TENS_0: 18.8% hit rate
SUGGESTED_TENS_0 = [n for n in range(100) if n // 10 == 0]

# STRONG_TENS_3: 18.8% hit rate
SUGGESTED_TENS_3 = [n for n in range(100) if n // 10 == 3]

# STRONG_TENS_5: 31.2% hit rate
SUGGESTED_TENS_5 = [n for n in range(100) if n // 10 == 5]

# Ones Digit Patterns
# STRONG_ONES_1: 18.8% hit rate
SUGGESTED_ONES_1 = [n for n in range(100) if n % 10 == 1]

# STRONG_ONES_4: 25.0% hit rate
SUGGESTED_ONES_4 = [n for n in range(100) if n % 10 == 4]

# STRONG_ONES_7: 25.0% hit rate
SUGGESTED_ONES_7 = [n for n in range(100) if n % 10 == 7]
